### PR TITLE
Add SQL checks

### PR DESCRIPTION
**Pull request by matthieudolci**
- Add SQL checks on the restored RDS database
- It is only build for Postgres a the moment

### CODE REVIEW

**Comment by russellballestrini** [comment]
@matthieudolci thank you, very cool. I'll review shortly.

**Comment by matthieudolci** [comment]
@russellballestrini Hi! Did you get a chance to review the PR?

**Comment by russellballestrini** [comment]
@matthieudolci I did, I was thinking it would be nice to use something like `sqlalchemy` so that we could support both MySQL and PostgreSQL.

**Comment by matthieudolci** [comment]
@russellballestrini Hi, we should probably close this PR. I won't have time to work on it anymore :-)

**Comment by russellballestrini** [comment]
Thanks for the PR, I don't have time to work on it either and it isn't _that_ essential to actually run SQL on the new cluster. The chances that it AWS cannot properly restore a snapshot are really low (like less than 1% but it is still possible.)

**Pull request closed without merging**
